sudo: required

language: c

matrix:
  include:
    - env: TEST_SUITE=testinstall GAPPKG=no
    - env: TEST_SUITE=testinstall GAPPKG=auto
    - env: TEST_SUITE=testinstall GAPPKG=all

    - env: TEST_SUITE=testbugfix GAPPKG=no
    - env: TEST_SUITE=testbugfix GAPPKG=auto
    - env: TEST_SUITE=testbugfix GAPPKG=all

    - env: TEST_SUITE=teststandard GAPPKG=no
    - env: TEST_SUITE=teststandard GAPPKG=auto
    - env: TEST_SUITE=teststandard GAPPKG=all

    - env: TEST_SUITE=testextra GAPPKG=no
    - env: TEST_SUITE=testextra GAPPKG=auto
    - env: TEST_SUITE=testextra GAPPKG=all

services:
  - docker

before_install:
- docker pull gapsystem/gap-docker-master

script:
    - docker version
    - docker run -v $PWD:/home/gap/travis/ gapsystem/gap-docker-master /bin/sh -c "TEST_SUITE=${TEST_SUITE} GAPPKG=${GAPPKG} /home/gap/travis/ci.sh"
